server:
    port: 8091

spring:
    liquibase:
        enabled: true
    profiles:
        active: dev
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5433/postgres
        username: ebok
        password: ebok
        hikari:
            poolName: Hikari
            auto-commit: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
